stages:
  - prepare
  - lint
  - test
  - compile
  - build
  - scan
  - deploy

variables:
  DOCKER_VERSION: '20.10'
  NODE_PACKAGE_REQUIRED: 'yes'

.ruby-cache: &ruby-cache
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby
  policy: pull

.ruby:
  image: ruby:$RUBY_VERSION
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - echo -e "\e[0Ksection_start:`date +%s`:bundle_install[collapsed=true]\r\e[0KBundle Install"
    - gem install bundler -v ${BUNDLER_VERSION:-2.3.20}
    - bundle config set --local force_ruby_platform false
    - bundle config set path 'vendor'
    - bundle install # Ensure Gem installed
    - echo -e "\e[0Ksection_end:`date +%s`:bundle_install\r\e[0K"
  cache:
    - <<: *ruby-cache

.node-cache: &node-cache
  key:
    files:
      - yarn.lock
      - package-lock.json
  paths:
    - node_modules
  policy: pull

.webdrivers-cache: &webdrivers-cache
  paths:
    - tmp/webdrivers
  policy: pull

.node:
  image: node:$NODE_VERSION
  before_script:
  cache:
    - <<: *node-cache

.install_node:
  # TODO: Improve Node.js install in Ruby image
  - if [[ "$NODE_PACKAGE_REQUIRED" == "yes" ]];
    then echo -e "\e[0Ksection_start:`date +%s`:setup_node[collapsed=true]\r\e[0KSetup Node.js"
    && curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz
    && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1
    && curl -o- -L https://yarnpkg.com/install.sh | bash
    && export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
    && echo -e "\e[0Ksection_end:`date +%s`:setup_node\r\e[0K";
    fi

.rails:
  extends: .ruby
  before_script:
    - !reference [.install_node]
    - !reference [.ruby, before_script]
  cache:
    - <<: *ruby-cache
    - <<: *node-cache
    - <<: *webdrivers-cache

.docker:
  image: docker:stable
  cache: {}
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:setup_docker[collapsed=true]\r\e[0KSetup Docker Buildx"
    - mkdir -p $HOME/.docker
    - mkdir -p /usr/libexec/docker/cli-plugins
    - wget https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-amd64
      -O /usr/libexec/docker/cli-plugins/docker-buildx
    - chmod +x /usr/libexec/docker/cli-plugins/docker-buildx
    - docker context create gitlab-ci
    - docker buildx create --use gitlab-ci # Enable cache export support
    - echo "$CI_JOB_TOKEN" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo -e "\e[0Ksection_end:`date +%s`:setup_docker\r\e[0K";
