stages:
  - prepare
  - lint
  - test
  - compile
  - build
  - scan
  - deploy

variables:
  NODE_PACKAGE_REQUIRED: 'yes'

.ruby-cache: &ruby-cache
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby
  policy: pull

.ruby:
  image: ruby:$RUBY_VERSION
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install bundler -v ${BUNDLER_VERSION:-2.2.28}
    - bundle config set path 'vendor'
    - bundle install # Ensure Gem installed
  cache:
    - <<: *ruby-cache

.node-cache: &node-cache
  key:
    files:
      - yarn.lock
      - package-lock.json
  paths:
    - node_modules
  policy: pull

.node:
  image: node:$NODE_VERSION
  before_script:
  cache:
    - <<: *node-cache

.install_node:
  # TODO: Improve Node.js install in Ruby image
  - if [[ "$NODE_PACKAGE_REQUIRED" == "yes" ]]; then curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1; fi
  - if [[ "$NODE_PACKAGE_REQUIRED" == "yes" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [[ "$NODE_PACKAGE_REQUIRED" == "yes" ]]; then export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH; fi

.rails:
  extends: .ruby
  before_script:
    - !reference [.install_node]
    - !reference [.ruby, before_script]
  cache:
    - <<: *ruby-cache
    - <<: *node-cache

.docker:
  image: docker:stable
  cache: {}
  services:
    - docker:20.10-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    IMAGE_NAME: $CI_REGISTRY_IMAGE
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  before_script:
    - mkdir -p $HOME/.docker
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
