stages:
  - lint
  - test
  - compile
  - build
  - scan

.ruby:
  image: ruby:$RUBY_VERSION
  before_script:
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - gem install bundler -v ${BUNDLER_VERSION:-2.2.28}
    - bundle config set path 'vendor'
    - bundle install
  cache:
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/ruby

.node:
  image: node:$NODE_VERSION
  before_script:
    - yarn install
  cache:
    key:
      files:
        - yarn.lock
        - package-lock.json
    paths:
      - node_modules

.rails:
  extends: .ruby
  before_script:
    # TODO: Improve Node.js install in Ruby image
    - curl -SLO https://nodejs.org/dist/v$NODE_VERSION/node-v${NODE_VERSION}-linux-x64.tar.xz && tar -xJf node-v${NODE_VERSION}-linux-x64.tar.xz -C /usr/local --strip-components=1;
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
    - !reference [.ruby, before_script]
    - !reference [.node, before_script]
  cache:
    key:
      files:
        - Gemfile.lock
        - yarn.lock
    paths:
      - vendor/ruby
      - node_modules

.docker:
  image: docker:stable
  cache: {}
  services:
    - docker:20.10-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
  before_script:
    - mkdir -p $HOME/.docker
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
