include:
  - remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/ruby.yml
  - remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/javascript.yml

stages:
  - lint
  - test
  - compile

variables:
  POSTGRES_VERSION: 12-alpine
  POSTGRES_DB: application
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/$POSTGRES_DB"

brakeman:
  extends: .ruby
  stage: lint
  script:
    - bundle exec brakeman

rspec:
  services:
    - postgres:$POSTGRES_VERSION
  before_script:
    - !reference [.ruby, before_script]
    - bundle exec rake db:migrate

assets:precompile:
  extends: .rails
  stage: compile
  services:
    - postgres:$POSTGRES_VERSION
  variables:
    RAILS_ENV: production
  script:
    - rails assets:precompile
  artifacts:
    paths:
      - public/packs
      - public/assets
  rules:
    - if: '$ASSETS_PRECOMPILE == "yes"'
