include:
  remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/common.yml

stages:
  - test

.rspec:
  extends:
    - .ruby
  script:
    - bundle exec rspec
  coverage: /\(\d+.\d+%\)/

rspec:
  extends: .rspec
  stage: test
