include:
  remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/common.yml

variables:
  RUBY_VERSION: 3.0.2

stages:
  - lint
  - test

rubocop:
  extends: .ruby
  stage: lint
  script:
    - bundle exec rubocop
  rules:
    - exists:
      - .rubocop.yml

bundler-audit:
  extends: .ruby
  stage: lint
  before_script:
    - gem install bundler-audit
    - bundle audit --update
  script:
    - bundle audit

bundler-leak:
  extends: .ruby
  stage: lint
  before_script:
    - gem install bundler-leak
    - bundle leak check --update
  script:
    - bundle leak

rspec:
  extends: .ruby
  stage: test
  script:
    - if [[ ! -v RSPEC_JUNIT_REPORT ]]; bundle exec rspec; fi
    - if [[ "$RSPEC_JUNIT_REPORT" == "yes" ]]; bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml; fi
  artifacts:
    paths:
      - coverage
      - rspec.xml
    reports:
      junit: rspec.xml
  coverage: '/\(\d+.\d+%\)/'
  rules:
    - exists:
      - spec/spec_helper.rb
