include:
  remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/common.yml

variables:
  RUBY_VERSION: 3.0.2

stages:
  - lint
  - test

bundler-audit:
  extends: .ruby
  stage: lint
  before_script:
    - gem install bundler-audit
    - bundle audit --update
  script:
    - bundle audit

bundler-leak:
  extends: .ruby
  stage: lint
  before_script:
    - gem install bundler-leak
    - bundle leak check --update
  script:
    - bundle leak

rspec:
  extends: .ruby
  stage: test
  script:
    - bundle exec rspec
  coverage: '/\(\d+.\d+%\)/'
